<img src="./img/oscon.png" width="400">

# Solutions for TensorFlow basics

# Hands-on .1

<img src="./img/hands_on_1.png" width="6000">

In [11]:
import tensorflow as tf
import numpy as np 

g = tf.Graph()
# graph A
with g.as_default():
    a = tf.constant(5)
    b = tf.constant(2)
    c = tf.constant(3)
    d = tf.multiply(a,b)
    e = tf.add(b,c)
    f = tf.subtract(d,e)
    with tf.Session() as sess:
        outs = sess.run([a,b,c,d,e,f])
        
print('Outputs for graph A: {}'.format(outs))
    
    
# graph B
with g.as_default():
    a = tf.constant(5,dtype=tf.float32)
    b = tf.constant(3,dtype=tf.float32)
    c = tf.multiply(a,b)
    d = tf.sin(c)
    e = tf.divide(b,d)
    with tf.Session() as sess:
        outs = sess.run([a,b,c,d,e])
        
print('Outputs for graph B: {}'.format(outs))

# graph C
with g.as_default():
    a = tf.constant(2,dtype=tf.int32)
    b = tf.constant(5,dtype=tf.int32)
    c = tf.multiply(a,b)
    d = tf.add(a,b)
    e = tf.floordiv(b,a)
    f = tf.subtract(d,e)
    with tf.Session() as sess:
        outs = sess.run([a,b,c,d,e,f])
        
print('Outputs for graph C: {}'.format(outs))

Outputs for graph A: [5, 2, 3, 10, 5, 5]
Outputs for graph B: [5.0, 3.0, 15.0, 0.65028787, 4.6133413]
Outputs for graph C: [2, 5, 10, 7, 2, 5]


# Hands-on .2

<img src="./img/hands_on_2_a.png" width="500">

In [8]:
with g.as_default():
    x = tf.constant([[5,3,2],[1,3,-5],[0,1,-8]],shape=[3,3],dtype=tf.float32)
    w = tf.constant([2,-5,4],shape=[3,1],dtype=tf.float32)
    c = tf.matmul(x,w)
    d = tf.reduce_sum(c)
    e = tf.reduce_mean(c)
    f = tf.reduce_max(c)
    with tf.Session() as sess:
        outs = sess.run([x,w,c,d,e,f])

print('Outputs for graph A:\n{}')
for n,out in zip(['x','w','c','d','e','f'],outs):        
    print('Node {} :\n{}'.format(n,out))


Outputs for graph A:
{}
Node x :
[[ 5.  3.  2.]
 [ 1.  3. -5.]
 [ 0.  1. -8.]]
Node w :
[[ 2.]
 [-5.]
 [ 4.]]
Node c :
[[  3.]
 [-33.]
 [-37.]]
Node d :
-67.0
Node e :
-22.3333339691
Node f :
3.0


# Hands-on .3

# Linear Regression

## $$f(x_i) = w^Tx_i +b$$
## $$y_i = f(x_i) + \epsilon_i$$

# Boston housing dataset

The Boston Housing dataset is a relatively small dataset (506 samples), containing information concerning housing in the area of Boston Massachusetts. There are 13 predictors and the target variable is the median value of owner-occupied homes in $1000's 

In [3]:
import tensorflow as tf 
from sklearn import datasets, metrics, preprocessing
boston = datasets.load_boston()
x_data = preprocessing.StandardScaler().fit_transform(boston.data)
y_data = boston.target
y_data = y_data.reshape(y_data.shape + (1,))

In [4]:
g = tf.Graph()
with g.as_default():
    x = tf.placeholder('float32',shape=None)
    y_true = tf.placeholder('float32',shape=None)

    with tf.name_scope('inference') as scope:
        w = tf.Variable(tf.truncated_normal([x_data.shape[1],1]),dtype='float32',name='weights')
        b = tf.Variable(tf.truncated_normal([1,1]),dtype='float32',name='bias')
        y_pred = tf.matmul(x,w) + b

    with tf.name_scope('loss') as scope:
        loss = tf.reduce_mean(tf.square(y_true-y_pred))

    with tf.name_scope('train') as scope:
        learning_rate = 0.1
        optimizer = tf.train.GradientDescentOptimizer(learning_rate)  
        train = optimizer.minimize(loss)

    init = tf.global_variables_initializer() 

    with tf.Session() as sess:
        sess.run(init)      
        for step in range(200):
            _,MSE = sess.run([train,loss],{x: x_data, 
                                           y_true: y_data})
print "MSE = {}".format(MSE)

MSE = 21.900384903
